# SITE CONFIGURATION
permalink: "/:title"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: randideo
  description: "Words & Doodles" # used by search engines
  
  # Google Drive CDN url
  images: https://googledrive.com/host/0B_BGvee0XueEcEkzeGJMd1FGdDQ/imgs/
  
  # BUILD SETTINGS
markdown: kramdown
highlighter: rouge
