url: "http://randideo.com" # the base hostname & protocol for your site
title: randideo
markdown: kramdown
highlighter: rouge
# Google Drive CDN url
images: https://googledrive.com/host/0B_BGvee0XueEcEkzeGJMd1FGdDQ/imgs/


